name: Bug report
description: Report a reproducible problem
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please provide enough detail to reproduce.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description of the problem
      placeholder: App crashes when...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps that trigger the issue
      placeholder: |
        1. Open...
        2. Tap...
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: input
    id: android_version
    attributes:
      label: Android version
      placeholder: Android 14
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      placeholder: Pixel 8
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Paste stack traces or add screenshots if available
